In [3807]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

import warnings
warnings.filterwarnings("ignore")

In [3808]:
from sklearn import datasets
iris=datasets.load_iris()
iris

{'data': array([[5.1, 3.5, 1.4, 0.2],
        [4.9, 3. , 1.4, 0.2],
        [4.7, 3.2, 1.3, 0.2],
        [4.6, 3.1, 1.5, 0.2],
        [5. , 3.6, 1.4, 0.2],
        [5.4, 3.9, 1.7, 0.4],
        [4.6, 3.4, 1.4, 0.3],
        [5. , 3.4, 1.5, 0.2],
        [4.4, 2.9, 1.4, 0.2],
        [4.9, 3.1, 1.5, 0.1],
        [5.4, 3.7, 1.5, 0.2],
        [4.8, 3.4, 1.6, 0.2],
        [4.8, 3. , 1.4, 0.1],
        [4.3, 3. , 1.1, 0.1],
        [5.8, 4. , 1.2, 0.2],
        [5.7, 4.4, 1.5, 0.4],
        [5.4, 3.9, 1.3, 0.4],
        [5.1, 3.5, 1.4, 0.3],
        [5.7, 3.8, 1.7, 0.3],
        [5.1, 3.8, 1.5, 0.3],
        [5.4, 3.4, 1.7, 0.2],
        [5.1, 3.7, 1.5, 0.4],
        [4.6, 3.6, 1. , 0.2],
        [5.1, 3.3, 1.7, 0.5],
        [4.8, 3.4, 1.9, 0.2],
        [5. , 3. , 1.6, 0.2],
        [5. , 3.4, 1.6, 0.4],
        [5.2, 3.5, 1.5, 0.2],
        [5.2, 3.4, 1.4, 0.2],
        [4.7, 3.2, 1.6, 0.2],
        [4.8, 3.1, 1.6, 0.2],
        [5.4, 3.4, 1.5, 0.4],
        [5.2, 4.1, 1.5, 0.1],
  

In [3809]:
iris.data

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [3810]:
iris.target

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [3811]:
iris.target_names

array(['setosa', 'versicolor', 'virginica'], dtype='<U10')

In [3812]:
X=iris.data
y=iris.target

In [3813]:
X

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [3814]:
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [3815]:
from sklearn.model_selection import train_test_split

In [3816]:
X_train,X_test,y_train,y_test=train_test_split(X,y,train_size=0.8, random_state=270)

In [3817]:
X_train

array([[6. , 2.2, 4. , 1. ],
       [5.1, 3.5, 1.4, 0.2],
       [6.3, 2.5, 5. , 1.9],
       [6.2, 2.9, 4.3, 1.3],
       [5.6, 3. , 4.5, 1.5],
       [6.7, 3. , 5. , 1.7],
       [7.3, 2.9, 6.3, 1.8],
       [7.2, 3.2, 6. , 1.8],
       [5.5, 2.4, 3.7, 1. ],
       [5.7, 3.8, 1.7, 0.3],
       [6.2, 2.8, 4.8, 1.8],
       [7.2, 3. , 5.8, 1.6],
       [6. , 2.2, 5. , 1.5],
       [4.9, 2.5, 4.5, 1.7],
       [5.7, 2.5, 5. , 2. ],
       [6.3, 3.3, 6. , 2.5],
       [5.9, 3. , 5.1, 1.8],
       [4.6, 3.4, 1.4, 0.3],
       [5.8, 2.7, 4.1, 1. ],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.8, 1.5, 0.3],
       [5. , 3.2, 1.2, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [6.3, 2.7, 4.9, 1.8],
       [5.4, 3.4, 1.5, 0.4],
       [6.1, 3. , 4.6, 1.4],
       [5.5, 2.6, 4.4, 1.2],
       [5.2, 3.5, 1.5, 0.2],
       [6. , 3.4, 4.5, 1.6],
       [6. , 2.7, 5.1, 1.6],
       [4.4, 3.2, 1.3, 0.2],
       [6.8, 2.8, 4.8, 1.4],
       [5.5, 3.5, 1.3, 0.2],
       [4.9, 3.1, 1.5, 0.2],
       [7.7, 2

In [3818]:
X_test

array([[5.7, 4.4, 1.5, 0.4],
       [5.4, 3.7, 1.5, 0.2],
       [6.7, 2.5, 5.8, 1.8],
       [7.1, 3. , 5.9, 2.1],
       [6.7, 3.3, 5.7, 2.5],
       [5.6, 3. , 4.1, 1.3],
       [4.4, 3. , 1.3, 0.2],
       [5.8, 2.6, 4. , 1.2],
       [6.3, 2.9, 5.6, 1.8],
       [5.7, 2.8, 4.5, 1.3],
       [4.9, 3.6, 1.4, 0.1],
       [6.4, 2.7, 5.3, 1.9],
       [4.3, 3. , 1.1, 0.1],
       [7.7, 3.8, 6.7, 2.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.1, 3.5, 1.4, 0.3],
       [7.9, 3.8, 6.4, 2. ],
       [6.4, 3.1, 5.5, 1.8],
       [6. , 3. , 4.8, 1.8],
       [5. , 2.3, 3.3, 1. ],
       [5. , 3. , 1.6, 0.2],
       [6.7, 3.1, 5.6, 2.4],
       [7.6, 3. , 6.6, 2.1],
       [6.9, 3.2, 5.7, 2.3],
       [5.7, 2.9, 4.2, 1.3],
       [5.1, 3.7, 1.5, 0.4],
       [6.6, 2.9, 4.6, 1.3],
       [6.9, 3.1, 5.4, 2.1],
       [5.9, 3. , 4.2, 1.5],
       [6.3, 3.4, 5.6, 2.4]])

In [3819]:
y_train

array([1, 0, 2, 1, 1, 1, 2, 2, 1, 0, 2, 2, 2, 2, 2, 2, 2, 0, 1, 0, 0, 0,
       0, 2, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 2, 1, 2, 0, 0, 1, 2, 2, 1, 1,
       0, 0, 0, 1, 2, 0, 1, 1, 0, 2, 1, 2, 2, 1, 0, 2, 1, 1, 0, 0, 1, 1,
       0, 2, 2, 2, 0, 2, 1, 2, 1, 0, 0, 1, 0, 1, 0, 1, 2, 2, 0, 0, 1, 0,
       2, 0, 1, 2, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 2, 0, 1, 2, 2, 2, 0, 2,
       2, 1, 0, 0, 1, 1, 2, 0, 1, 0])

In [3820]:
y_test

array([0, 0, 2, 2, 2, 1, 0, 1, 2, 1, 0, 2, 0, 2, 0, 0, 2, 2, 2, 1, 0, 2,
       2, 2, 1, 0, 1, 2, 1, 2])

In [3821]:
from sklearn.preprocessing import StandardScaler, MinMaxScaler, RobustScaler

In [3822]:
rs=RobustScaler()
##mm=MinMaxScaler()
##sc=StandardScaler()

In [3823]:
X_train=rs.fit_transform(X_train)
##X_train=mm.fit_transform(X_train)
##X_train=sc.fit_transform(X_train)

In [3824]:
X_train

array([[ 0.20408163, -1.6       , -0.08759124, -0.2       ],
       [-0.53061224,  1.        , -0.84671533, -0.73333333],
       [ 0.44897959, -1.        ,  0.20437956,  0.4       ],
       [ 0.36734694, -0.2       ,  0.        ,  0.        ],
       [-0.12244898,  0.        ,  0.05839416,  0.13333333],
       [ 0.7755102 ,  0.        ,  0.20437956,  0.26666667],
       [ 1.26530612, -0.2       ,  0.58394161,  0.33333333],
       [ 1.18367347,  0.4       ,  0.49635036,  0.33333333],
       [-0.20408163, -1.2       , -0.17518248, -0.2       ],
       [-0.04081633,  1.6       , -0.75912409, -0.66666667],
       [ 0.36734694, -0.4       ,  0.1459854 ,  0.33333333],
       [ 1.18367347,  0.        ,  0.4379562 ,  0.2       ],
       [ 0.20408163, -1.6       ,  0.20437956,  0.13333333],
       [-0.69387755, -1.        ,  0.05839416,  0.26666667],
       [-0.04081633, -1.        ,  0.20437956,  0.46666667],
       [ 0.44897959,  0.6       ,  0.49635036,  0.8       ],
       [ 0.12244898,  0.

In [3825]:
X_test=rs.transform(X_test)
##X_test=mm.transform(X_test)
##X_test=sc.transform(X_test)

In [3826]:
X_test

array([[-0.04081633,  2.8       , -0.81751825, -0.6       ],
       [-0.28571429,  1.4       , -0.81751825, -0.73333333],
       [ 0.7755102 , -1.        ,  0.4379562 ,  0.33333333],
       [ 1.10204082,  0.        ,  0.46715328,  0.53333333],
       [ 0.7755102 ,  0.6       ,  0.40875912,  0.8       ],
       [-0.12244898,  0.        , -0.05839416,  0.        ],
       [-1.10204082,  0.        , -0.87591241, -0.73333333],
       [ 0.04081633, -0.8       , -0.08759124, -0.06666667],
       [ 0.44897959, -0.2       ,  0.37956204,  0.33333333],
       [-0.04081633, -0.4       ,  0.05839416,  0.        ],
       [-0.69387755,  1.2       , -0.84671533, -0.8       ],
       [ 0.53061224, -0.6       ,  0.2919708 ,  0.4       ],
       [-1.18367347,  0.        , -0.93430657, -0.8       ],
       [ 1.59183673,  1.6       ,  0.70072993,  0.6       ],
       [-0.7755102 ,  0.2       , -0.78832117, -0.73333333],
       [-0.53061224,  1.        , -0.84671533, -0.66666667],
       [ 1.75510204,  1.

In [3827]:
from sklearn.linear_model import LogisticRegression

In [3828]:
logr=LogisticRegression(multi_class='ovr')

In [3829]:
model=logr.fit(X_train,y_train)

In [3830]:
model.predict(X_test)

array([0, 0, 2, 2, 2, 1, 0, 1, 2, 1, 0, 2, 0, 2, 0, 0, 2, 2, 2, 1, 0, 2,
       2, 2, 1, 0, 1, 2, 1, 2])

In [3831]:
model.predict_proba(X_test)

array([[9.86129646e-01, 1.19411751e-02, 1.92917891e-03],
       [9.27069550e-01, 7.13290477e-02, 1.60140244e-03],
       [8.89385995e-04, 4.84202023e-01, 5.14908591e-01],
       [1.77846854e-03, 3.19584729e-01, 6.78636802e-01],
       [6.28385391e-03, 1.61081316e-01, 8.32634830e-01],
       [2.17751303e-01, 5.43916048e-01, 2.38332650e-01],
       [7.76984717e-01, 2.21878742e-01, 1.13654007e-03],
       [4.76039716e-02, 7.66682854e-01, 1.85713174e-01],
       [8.12211307e-03, 3.92453412e-01, 5.99424475e-01],
       [7.19462396e-02, 6.49537706e-01, 2.78516054e-01],
       [9.20093856e-01, 7.89139918e-02, 9.92151775e-04],
       [3.54091714e-03, 4.40351666e-01, 5.56107417e-01],
       [7.81956460e-01, 2.17285394e-01, 7.58146092e-04],
       [6.00871640e-03, 9.11277606e-02, 9.02863523e-01],
       [7.82859751e-01, 2.15495588e-01, 1.64466133e-03],
       [8.99935242e-01, 9.82937157e-02, 1.77104222e-03],
       [7.18593141e-03, 1.06465299e-01, 8.86348770e-01],
       [1.57827595e-02, 3.26012

In [3832]:
y_pred=model.predict(X_test)

In [3833]:
y_pred

array([0, 0, 2, 2, 2, 1, 0, 1, 2, 1, 0, 2, 0, 2, 0, 0, 2, 2, 2, 1, 0, 2,
       2, 2, 1, 0, 1, 2, 1, 2])

In [3834]:
y_train_pred=model.predict(X_train)

In [3835]:
y_train_pred

array([1, 0, 2, 1, 1, 2, 2, 2, 1, 0, 2, 2, 1, 1, 2, 2, 2, 0, 1, 0, 0, 0,
       0, 2, 0, 1, 1, 0, 2, 1, 0, 1, 0, 0, 2, 1, 2, 0, 0, 1, 2, 2, 2, 1,
       0, 1, 0, 1, 2, 0, 1, 1, 0, 2, 1, 2, 2, 2, 0, 2, 2, 1, 0, 0, 1, 1,
       0, 2, 2, 2, 0, 2, 2, 2, 2, 0, 0, 1, 0, 2, 0, 1, 2, 2, 0, 0, 1, 0,
       2, 0, 1, 2, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 2, 0, 1, 2, 1, 2, 0, 2,
       2, 1, 0, 0, 1, 1, 1, 0, 1, 0])

In [3836]:
from sklearn.metrics import accuracy_score

In [3837]:
print(accuracy_score(y_train,y_train_pred),accuracy_score(y_test,y_pred))

0.8916666666666667 1.0
